<#macro people>
<#if to>tourists<#else>people</#if>
</#macro>
<#macro People>
<#if to>Tourists<#else>People</#if>
</#macro>

<#if (random < 50)>
In Figure \ref{fig:cdr-stats-${city}-${month}<#if to>-tourist</#if>} we show results for ${city} in ${month}.
<#else>
Figure \ref{fig:cdr-stats-${city}-${month}<#if to>-tourist</#if>} shows results for ${city} in ${month}.
</#if>
In Figure \ref{fig:cdr-stats-${city}-${month}<#if to>-tourist</#if>}(a) it is possible to see that almost all the <@people/> produce at leat one CDR per day allowing to evaluate their presence in 
a given area. <#if !to>This allows to understand if users are tourists of residents on the basis of the amount of time spent in the city.</#if>


Figure \ref{fig:cdr-stats-${city}-${month}<#if to>-tourist</#if>}(b) illustrates the radius of gyration. 
The fist ${cityRPercentile}$^{th}$ percentile has a radius of gyration about the size of ${city}'s radius (${cityR/1000} km). These are <@people/> staying mainly within the city center.
<@People/> in the ${cityRPercentile}$^{th}$ - ${city2RPercentile}$^{th}$ percentile range are associated to <@people/> travelling mainly within the city diameter. 
It is worth noting that if the number of CDR generated by the user is low, the radius of gyration can be rather biased toward those few data points.
<#if city=='Venezia'>For example, Venice airport is located at 10Km from Venice island possibly inflating the radius of gyration for tourists.</#if>
<#if city=='Firenze'>For example, while Florence airport is located at only 5Km from city center, Bologna airport the main hub for the region is at about 40Km distance. 
<@People/> arriving in Bologna and generating few CDR would have a large radius even if they actually stay for the whole time in Florence center.</#if>
<@People/> above the ${city2RPercentile}$^{th}$ percentile tend to travel acorss the whole region.



Figure \ref{fig:cdr-stats-${city}-${month}<#if to>-tourist</#if>}(c) illustrates the number of days of presence in the area for a given percentile of <@people/>. 
<#if (days_75p < 5)>
It is possible to see that the majority of <@people/> remains in the area for less than ${days_75p} days, 
associated to a typical tourist destination (official statistics estimate that tourists stay in the city for 2-3 days). 
<#elseif (days_75p < 10)>
The majority of the <@people/> remains in the area for less than ${days_75p} days. This indicates a sort of mixed area having a strongly tourist compoenet, but also a large number of people living in there.
<#else>
We can see that the number of days in the area is rather large. This indicates that the city is not a mainly turist area<#if !to>, but is has a large component of poeple living in there</#if>.
</#if>  





Figure \ref{fig:cdr-stats-${city}-${month}<#if to>-tourist</#if>}(d) illustrates <@people/> composition by nationality.  It is possible to see that although
<#switch top_country>
  <#case "IT">Italians<#break>
  <#case "FR">French people<#break>
</#switch>  
 are the major cut (${top_country_prob}\%)
<#if (top_country_prob > 40)>by far</#if>, the remaining ${100-top_country_prob}\% of the <@people/> are likely to be foreigner. 



\begin{figure}[H]
\begin{center}
a)\includegraphics[width=0.45\columnwidth,height=5cm]{${filecdr}}
b)\includegraphics[width=0.45\columnwidth,height=5cm]{${fileradius}}\\
c)\includegraphics[width=0.45\columnwidth,height=5cm]{${filedays}}
d)\includegraphics[width=0.45\columnwidth,height=5cm]{${filecountries}}\\
\end{center}
\caption{{\bf ${city} in ${month}} <#if to>- Tourist Only</#if> . {\bf (a)} Daily average number of CDR. {\bf (b)} Radius of gyration. {\bf (c)} Number of days in the area. {\bf (d)} Percentage of <@people/> by country}
\label{fig:cdr-stats-${city}-${month}<#if to>-tourist</#if>}
\end{figure}